language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: ntITlJSfwkcsBBpvbEV/DvfmV+DWfAdyHfv8FS7mGFIayrVa8qalDwW/ImNV/FGev4qbqrPBMJmD3PFB6yLlIk9Inn28Uq+cg0NRSLNHGh9OPItB4XUy0i51itfcLvqKDbX3YHDI7KILg588vmjp/B1npvTqIhzPaPQx9mqEcwE=
  - secure: dVawU1fxa2ftk3WjBY/59uDumzCoUbBwtAWFlewTr0zcfA51xvksfyy9ipuC1B1/PJWWMTmJj8iNn7zBVXp/GIWXV6k4aj4umE9GxUEnt+gcdIX0wgrKPijPzdqVXmNNPYwdYVqcnhsYLsIqp6xFkBon/Lgb9swkNeccFmxBTQI=
  - secure: FBsnKtCoqoX96T7NOobyf1HtWb10iL9wyt5L2GIJe4PjEHU3k1NOGsYptjyRf6ljLComQGk86f1nPmZyVm7+tTmyOcIS3yVKSZfPVGcfG1xRv2M1lGT1TT45Ko7OrYXPxNTPbBi40MHq0V+giQZSsK8T3Bmp3hL828Vfe7rKjko=
  - secure: PjO4jH8bcSt3XeLU7iH5zzrUK4SjYJP8knUvUtApvHK9jPHV/2oJ3y8mrocxU1jMlGMG7odrv3N9fcbavbXw6qwZ2d6hCMp4MIoehd4+2ydzSckuLpGOrjqKIG4FJlJGW5bnoYKMvjVVUlf092xQRikqanAPvaC/uNf8cTExfuM=
