language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: F0FJcYV7qRxQPERQPJECvWFiIUIlSVFh+nng0FiBUEQb0SGaZ+cmrgp+Wu2BGygph+yRpdXqi755ZtIeK36PBRvqJLMLMm/V86FifcHMBicq1R/3WCiBJOHzeru5ZNeloNhCNf68AjgdfgC5HmJBi877VNLY7WuNhUawQPCaUhM=
  - secure: IE6DxAVx8P7oy8L9QSvWSPiG0YKR7W6cmv+SWR7F/N6BYz4bhDk6we+pYg/j6sP96cNOQi2lVxLj9NeKYx2XKePX3TEjanRkRr+eaM19sz68m9VyqgWUaj8SJb2Jy0VU1ZlvgCLuSBKQlbMIFeMHsIeuC9GjZZpo7Vc0aCI3EEw=
